export const theme = {
  PRIMARY_COLOR: '#00B2A9',
  ACCENT_COLOR: '#2AB8D1',
  RED_COLOR: '#FF3333',
  FONT_WEIGHT_LIGHT: '200',
  FONT_WEIGHT_MEDIUM: '500',
  FONT_WEIGHT_BOLD: '700'
};

// FONT_SIZE_SMALL: 12,
// FONT_SIZE_MEDIUM: 14,
// FONT_SIZE_LARGE: 16,
// CONTAINER_PADDING: 20
