export const theme = {
  PRIMARY_COLOR: '#006DA8',
  ACCENT_COLOR: '#2AB8D1',
  RED_COLOR: '#FF3333'
};

// FONT_SIZE_SMALL: 12,
// FONT_SIZE_MEDIUM: 14,
// FONT_SIZE_LARGE: 16,
// FONT_WEIGHT_LIGHT: '200',
// FONT_WEIGHT_MEDIUM: '500',
// FONT_WEIGHT_BOLD: '700',
// CONTAINER_PADDING: 20
